<?php

namespace Database\Seeders;

use App\Models\Color;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ColorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('colors')->insert([
            ['name' => 'AliceBlue', 'hex_code' => '#F0F8FF'],
            ['name' => 'AntiqueWhite', 'hex_code' => '#FAEBD7'],
            ['name' => 'Aqua', 'hex_code' => '#00FFFF'],
            ['name' => 'Aquamarine', 'hex_code' => '#7FFFD4'],
            ['name' => 'Azure', 'hex_code' => '#F0FFFF'],
            ['name' => 'Beige', 'hex_code' => '#F5F5DC'],
            ['name' => 'Bisque', 'hex_code' => '#FFE4C4'],
            ['name' => 'Black', 'hex_code' => '#000000'],
            ['name' => 'BlanchedAlmond', 'hex_code' => '#FFEBCD'],
            ['name' => 'Blue', 'hex_code' => '#0000FF'],
            ['name' => 'BlueViolet', 'hex_code' => '#8A2BE2'],
            ['name' => 'Brown', 'hex_code' => '#A52A2A'],
            ['name' => 'BurlyWood', 'hex_code' => '#DEB887'],
            ['name' => 'CadetBlue', 'hex_code' => '#5F9EA0'],
            ['name' => 'Chartreuse', 'hex_code' => '#7FFF00'],
            ['name' => 'Chocolate', 'hex_code' => '#D2691E'],
            ['name' => 'Coral', 'hex_code' => '#FF7F50'],
            ['name' => 'CornflowerBlue', 'hex_code' => '#6495ED'],
            ['name' => 'Cornsilk', 'hex_code' => '#FFF8DC'],
            ['name' => 'Crimson', 'hex_code' => '#DC143C'],
            ['name' => 'Cyan', 'hex_code' => '#00FFFF'],
            ['name' => 'DarkBlue', 'hex_code' => '#00008B'],
            ['name' => 'DarkCyan', 'hex_code' => '#008B8B'],
            ['name' => 'DarkGoldenrod', 'hex_code' => '#B8860B'],
            ['name' => 'DarkGray', 'hex_code' => '#A9A9A9'],
            ['name' => 'DarkGrey', 'hex_code' => '#A9A9A9'],
            ['name' => 'DarkGreen', 'hex_code' => '#006400'],
            ['name' => 'DarkKhaki', 'hex_code' => '#BDB76B'],
            ['name' => 'DarkMagenta', 'hex_code' => '#8B008B'],
            ['name' => 'DarkOliveGreen', 'hex_code' => '#556B2F'],
            ['name' => 'DarkOrange', 'hex_code' => '#FF8C00'],
            ['name' => 'DarkOrchid', 'hex_code' => '#9932CC'],
            ['name' => 'DarkRed', 'hex_code' => '#8B0000'],
            ['name' => 'DarkSalmon', 'hex_code' => '#E9967A'],
            ['name' => 'DarkSeaGreen', 'hex_code' => '#8FBC8F'],
            ['name' => 'DarkSlateBlue', 'hex_code' => '#483D8B'],
            ['name' => 'DarkSlateGray', 'hex_code' => '#2F4F4F'],
            ['name' => 'DarkSlateGrey', 'hex_code' => '#2F4F4F'],
            ['name' => 'DarkTurquoise', 'hex_code' => '#00CED1'],
            ['name' => 'DarkViolet', 'hex_code' => '#9400D3'],
            ['name' => 'DeepPink', 'hex_code' => '#FF1493'],
            ['name' => 'DeepSkyBlue', 'hex_code' => '#00BFFF'],
            ['name' => 'DimGray', 'hex_code' => '#696969'],
            ['name' => 'DimGrey', 'hex_code' => '#696969'],
            ['name' => 'DodgerBlue', 'hex_code' => '#1E90FF'],
            ['name' => 'FireBrick', 'hex_code' => '#B22222'],
            ['name' => 'FloralWhite', 'hex_code' => '#FFFAF0'],
            ['name' => 'ForestGreen', 'hex_code' => '#228B22'],
            ['name' => 'Fuchsia', 'hex_code' => '#FF00FF'],
            ['name' => 'Gainsboro', 'hex_code' => '#DCDCDC'],
            ['name' => 'GhostWhite', 'hex_code' => '#F8F8FF'],
            ['name' => 'Gold', 'hex_code' => '#FFD700'],
            ['name' => 'Goldenrod', 'hex_code' => '#DAA520'],
            ['name' => 'Gray', 'hex_code' => '#808080'],
            ['name' => 'Grey', 'hex_code' => '#808080'],
            ['name' => 'Green', 'hex_code' => '#008000'],
            ['name' => 'GreenYellow', 'hex_code' => '#ADFF2F'],
            ['name' => 'Honeydew', 'hex_code' => '#F0FFF0'],
            ['name' => 'HotPink', 'hex_code' => '#FF69B4'],
            ['name' => 'IndianRed', 'hex_code' => '#CD5C5C'],
            ['name' => 'Indigo', 'hex_code' => '#4B0082'],
            ['name' => 'Ivory', 'hex_code' => '#FFFFF0'],
            ['name' => 'Khaki', 'hex_code' => '#F0E68C'],
            ['name' => 'Lavender', 'hex_code' => '#E6E6FA'],
            ['name' => 'LavenderBlush', 'hex_code' => '#FFF0F5'],
            ['name' => 'LawnGreen', 'hex_code' => '#7CFC00'],
            ['name' => 'LemonChiffon', 'hex_code' => '#FFFACD'],
            ['name' => 'LightBlue', 'hex_code' => '#ADD8E6'],
            ['name' => 'LightCoral', 'hex_code' => '#F08080'],
            ['name' => 'LightCyan', 'hex_code' => '#E0FFFF'],
            ['name' => 'LightGoldenrodYellow', 'hex_code' => '#FAFAD2'],
            ['name' => 'LightGray', 'hex_code' => '#D3D3D3'],
            ['name' => 'LightGrey', 'hex_code' => '#D3D3D3'],
            ['name' => 'LightGreen', 'hex_code' => '#90EE90'],
            ['name' => 'LightPink', 'hex_code' => '#FFB6C1'],
            ['name' => 'LightSalmon', 'hex_code' => '#FFA07A'],
            ['name' => 'LightSeaGreen', 'hex_code' => '#20B2AA'],
            ['name' => 'LightSkyBlue', 'hex_code' => '#87CEFA'],
            ['name' => 'LightSlateGray', 'hex_code' => '#778899'],
            ['name' => 'LightSlateGrey', 'hex_code' => '#778899'],
            ['name' => 'LightSteelBlue', 'hex_code' => '#B0C4DE'],
            ['name' => 'LightYellow', 'hex_code' => '#FFFFE0'],
            ['name' => 'Lime', 'hex_code' => '#00FF00'],
            ['name' => 'LimeGreen', 'hex_code' => '#32CD32'],
            ['name' => 'Linen', 'hex_code' => '#FAF0E6'],
            ['name' => 'Magenta', 'hex_code' => '#FF00FF'],
            ['name' => 'Maroon', 'hex_code' => '#800000'],
            ['name' => 'MediumAquamarine', 'hex_code' => '#66CDAA'],
            ['name' => 'MediumBlue', 'hex_code' => '#0000CD'],
            ['name' => 'MediumOrchid', 'hex_code' => '#BA55D3'],
            ['name' => 'MediumPurple', 'hex_code' => '#9370DB'],
            ['name' => 'MediumSeaGreen', 'hex_code' => '#3CB371'],
            ['name' => 'MediumSlateBlue', 'hex_code' => '#7B68EE'],
            ['name' => 'MediumSpringGreen', 'hex_code' => '#00FA9A'],
            ['name' => 'MediumTurquoise', 'hex_code' => '#48D1CC'],
            ['name' => 'MediumVioletRed', 'hex_code' => '#C71585'],
            ['name' => 'MidnightBlue', 'hex_code' => '#191970'],
            ['name' => 'MintCream', 'hex_code' => '#F5FFFA'],
            ['name' => 'Violet', 'hex_code' => '#EE82EE'],
            ['name' => 'Wheat', 'hex_code' => '#F5DEB3'],
            ['name' => 'White', 'hex_code' => '#FFFFFF'],
            ['name' => 'WhiteSmoke', 'hex_code' => '#F5F5F5'],
            ['name' => 'Yellow', 'hex_code' => '#FFFF00'],
            ['name' => 'YellowGreen', 'hex_code' => '#9ACD32'],
        ]);
    }
}
